### ISSUE TITLE
Errors in the HTML scan default to vanilla score

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-space#101]
The instance https://search.trom.tf is known to load external resources but it just got a vanilla score because the HTML scan failed:
```
Message: Reached error page: about:neterror?e=connectionFailure&u=https%3A//search.trom.tf/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20search.trom.tf. 
```

<img width="602" alt="image" src="https://user-images.githubusercontent.com/4016501/154914016-c7fd84b7-ad74-4bf7-93ca-e91a40021ec1.png">

**Comment by return42** [comment]
@unixfox can we close this issue? ...

![image](https://user-images.githubusercontent.com/554536/177134493-91cb537b-19e9-4e9c-8dba-54140dcb02da.png)

BTW: both engines have some issues ..

![image](https://user-images.githubusercontent.com/554536/177134746-4e229034-ca9d-48cb-95c4-737666c3c2c1.png)

![image](https://user-images.githubusercontent.com/554536/177135966-bcc8a371-4328-4462-8f01-1c88179dc790.png)
