### ISSUE TITLE
searx or searxng or other

### ISSUE THREAD

**Issue by Mennaruuk** [searxng/searx-space#104]
May you please include a new column specifying the type of search engine, whether it's SearX, SearXNG, or a different fork of either? Thanks!

**Comment by unixfox** [comment]
For the moment hover the mouse on the HTML column and most of the time this will tell you if it's a searx or searxng instance.

**Comment by unixfox** [comment]
Closing as we are going to remove searx instances from the list: https://github.com/searxng/searx-instances/discussions/336
