### ISSUE TITLE
Add link to donate to SearXNG.

### ISSUE THREAD

**Issue by vojkovic** [searxng/searx-space#112]
As the donation link is shown by default in every searxng instance, you should also consider putting a link to donate somewhere in searx.space. 

In my opinion, this could be in the top right, next to about.

**Comment by unixfox** [comment]
@dalf I think this is trivial to implement.

**Comment by vojkovic** [comment]
Looks like the searxng team is no longer accepting donations, so I guess this can be closed as unplanned.
