### ISSUE TITLE
Update Favicon with SearXNG logo

### ISSUE THREAD

**Issue by return42** [searxng/searx-space#113]
The searx.space side is hosted by the SearXNG team (searxng.org) / the favicon of searx.space should be updated by the [SearXNG logo](https://github.com/searxng/searxng/blob/master/src/brand/searxng-wordmark.svg). The old favicon is from former searx project and is somtimes a bit missleading (e.g. in Matrix):

![image](https://user-images.githubusercontent.com/554536/177131294-fd323aea-bd0c-45d6-bf1f-f7d97275e79a.png)

**Comment by dalf** [comment]
Fixed with #98
