### ISSUE TITLE
DNS Cache

### ISSUE THREAD

**Issue by vvaadim** [searxng/searx-space#116]
hey,
appears that the server searx.space is running on has very long time dns cache, I have changed my DNS provider 2 days ago now and it appears that searx.space is still trying to connect to the temp IP i put in there in the beginning.
other dns resolvers seem to resolve it perfectly, https://dnschecker.org/#A/searx.priv.pw
the domain I'm talking about is "searx.priv.pw" (my Onion mirror appears to works fine)

**Comment by unixfox** [comment]
Could be something else than the DNS cache, like your instance not responding at the time of the scan.

Anyway it seems like it's fixed and your instance is now listed.

**Comment by unixfox** [comment]
@dalf any comment about this?

**Comment by dalf** [comment]
The [unbound configuration](https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/) uses the default values:
```
    cache-min-ttl: 3600
    cache-max-ttl: 86400
```

But the Python has also a cache with a one day expiration:
https://github.com/searxng/searx-space/blob/b067de9878f338768ac922c232aaa1f181ca71c7/searxstats/fetcher/network.py#L116

The value should be lower.

**Comment by dalf** [comment]
Close by https://github.com/searxng/searx-space/pull/123 : the cache delay is now one hour instead of one day.

**Comment by vvaadim** [comment]
Hey, posting as it just happened again.
Its been 2 days now since I changed my DNS provider and its still unreachable by searx.space
https://dnschecker.org/#NS/priv.pw its propagated pretty much everywhere

**Comment by vvaadim** [comment]
@dalf @unixfox

**Comment by vvaadim** [comment]
seems like its back up.
