### ISSUE TITLE
Api call not working in mobile android

### ISSUE THREAD

**Issue by lisawebcoder** [searxng/searx-space#117]
Hello
I made an api call web app for your endpoints but while it returns json in desktop computer for the mobile phone i get no request or response header and 0 as response for GET

**Comment by return42** [comment]
Can you show us your project?

**Comment by lisawebcoder** [comment]
Ok i will go to my computer

**Comment by dalf** [comment]
If you are talking about https://searx.space/data/instances.json : it is just a HTTP server and a static file, nothing more.
Whatever the HTTP client (HTTP/1 or HTTP/2), it should work.

If relevant, you can try to disable HTTP/2 or use a different compression (Deflate rather than Brotli).

**Comment by lisawebcoder** [comment]
![Capture+_2022-07-26-11-49-49_resized](https://user-images.githubusercontent.com/49798411/181052163-5c52b96e-6c38-42f5-8ccf-f9711f6087ed.png)
b51dde.png)

**Comment by lisawebcoder** [comment]
![Capture+_2022-07-25-22-47-34_resized](https://user-images.githubusercontent.com/49798411/181052271-52060eb3-ae9e-4aa1-80dd-62873b3189f3.png)

**Comment by lisawebcoder** [comment]
no output on either response; 1st pic has no response or request at all; 2nd pic hass 200 ok but its sending html inspite i put paramter &format=json and so no output to browser again 
this is all on mobile
on desktop my webapp works

**Comment by lisawebcoder** [comment]
hello dalf
---------------------------------
If you are talking about https://searx.space/data/instances.json : it is just a HTTP server and a static file, nothing more.
Whatever the HTTP client (HTTP/1 or HTTP/2), it should work.

If relevant, you can try to disable HTTP/2 or use a different compression (Deflate rather than Brotli).
-----------------------------------
no i made my own webapp; see the domain above
it works on desktop the api cal i wrote in my code but not on mobile android phone whether on data or wifi
sorry i dont understand your answer

lisa

**Comment by return42** [comment]
> Ok i will go to my computer

I asked for the source code to see what requests you are build.

**Comment by lisawebcoder** [comment]
ok i will put source code

**Comment by return42** [comment]
Why not versioning in your account https://github.com/lisawebcoder?tab=repositories

**Comment by lisawebcoder** [comment]
hello reurtn42 what do you mean?
i dont know how to upload my code here

**Comment by lisawebcoder** [comment]
i pretty sure if you do page source you can see my html and then click the JS file 
its all there

**Comment by lisawebcoder** [comment]
i know how to push code w/ git commands but i am not on cli right now

**Comment by lisawebcoder** [comment]
sorry im trying to push the code but i am getting erros ; i wil try later

**Comment by unixfox** [comment]
Please stop spamming the comments. You can edit a previous comment and we will see the edited text.

I think you should join our matrix or IRC channel to diagnose your issue it will be easier: https://github.com/searxng/searxng#contact

**Comment by lisawebcoder** [comment]
this is not spam ok
i am totally confused now
searx.org and now searxng.org
which i tried endpoints and it s doesnt work at all
at least searx.org endpoints  work
this is how a thread works
answere and rsponse
its not spam ok
lisa


------

added comment

why is this endpoint not working?
https://searxng.org/search?q=baseball
but this does
https://searx.org/search?q=baseball

---
new commnet
i modifyied the endpoint to this
https://docs.searxng.org/search?q=baseball
but it doesnt search single words?
im getting more lost
ok i will try later and return thxz


here is the repo link to my source code
https://github.com/lisawebcoder/test1july2022

**Comment by dalf** [comment]
* https://docs.searxng.org is the documentation about SearXNG ==> This is not a SearXNG instance, you won't be able to get search engine results from this website.
* https://searx.org is old searx instance (from https://github.com/searx/searx : notice there is no "ng").

---

* To use a recent instance, pick on the instance on the top of the list of https://searx.space/ . However most of them won't support the [`&format=json`](https://github.com/lisawebcoder/test1july2022/blob/3de7baeb2603ee340c1c1f11d711c3f2fcad315f/weather.js#L27) parameter to avoid bots.
* So if you want to do some experiment with XMLHttpRequest, keep searx.org

**Comment by lisawebcoder** [comment]
Ok thank you
So i will work with the endpoint searx.org
Just waiting for comment to help with my mobile errors
Thank you

**Comment by dalf** [comment]
We don't own or maintain searx.org, so we can't say.
Perhaps searx.org doesn't allow mobile user agents.
I close the issue since the initial question is answered.

**Comment by lisawebcoder** [comment]
Why is this closed?
The initial question is NOT answered sorry but it's not 

I asked why is the API not return any json and i was asked to post my source code which i did ok

**Comment by dalf** [comment]
We are not responsible of searx.org, so we can't help you.

**Comment by lisawebcoder** [comment]
Hello
Ok i am not getting this
On searx.org it sent me here to ask questions
So let others answer
Please open my question
Thank you

**Comment by return42** [comment]
> On searx.org it sent me here to ask questions

This is your issue, you need to understand that we are not responsible for searx.org, we are not the owner of this domain, we do not know who is the owner and the search engine on this domain does use searx ... not SearXNG from our org .. and this thread is placed in searx-space 

To shorten up: searx-space does not have the API you asked for, you are completely wrong here.

> Please open my question

.. we can't help .. please accept these facts.
