### ISSUE TITLE
remove Searxes from the "about" tab?

### ISSUE THREAD

**Issue by maninthemiddle01** [searxng/searx-space#120]
The onion-URL is not found by Tor-Browser and not working anymore.

**Comment by unixfox** [comment]
@dalf what do you think about this?

**Comment by return42** [comment]
@Danwin are you the maintainer of http://searxes.wodferndripvpe6ib4uz4rtngrnzichnirgn7t5x64gxcyroopbhsuqd.onion/ ?

**Comment by DanWin** [comment]
@return42 , no I'm not maintaining it, but I provide the server it is/was running on.

**Comment by dalf** [comment]
If the service is offline, we can remove it.

@DanWin do you think it will be online again?

**Comment by DanWin** [comment]
I've pinged the maintainers, might take a while to get an answer.
