### ISSUE TITLE
Instance data not updating every 24h

### ISSUE THREAD

**Issue by Niveshkrishna** [searxng/searx-space#127]
I noticed that instance data is not refreshed after 24 hours. There was a new [release](https://gitlab.e.foundation/e/infra/spot/-/releases/v2.3.5+20221115) of spot.murena.io couple of days back and yet data is not refreshed. 

Could someone check if the scheduled job is running as expected?

Thanks

**Comment by dalf** [comment]
Fixed: 
* the code fetches the git repositories of the various searx / SearXNG forks.
* fetch_git.py has issue to deal with repository when there is a push force on the master branch.
* I've removed the git repositories on check.searx.space as a workaround.
 
I've opened an issue about the cause: https://github.com/searxng/searx-space/issues/128
