### ISSUE TITLE
Wrong country detection on multiple instances

### ISSUE THREAD

**Issue by nicfab** [searxng/searx-space#135]
Multiple instances have wrong countries, such as IE (ireland):
![image](https://user-images.githubusercontent.com/4016501/215488421-575a1053-2e50-4fe2-ad3a-6e051dcbc9af.png)
![image](https://user-images.githubusercontent.com/4016501/215491315-cc3b9a6c-d846-4937-b553-262dc2657726.png)

@dalf Maybe the geoip database wasn't migrated properly from the old VPS?

-----
On the public instances webpage, I see that my instance (https://searxng.nicfab.eu/) in the column Country has the value **US, IE**.
Why? 
**My instance is on AWS Italy, which is located in Milan.**
There is an error.
Could you please review it?
Please also remove the red background on AWS instances like mine.

**Comment by dalf** [comment]
> Maybe the geoip database wasn't migrated properly from the old VPS?

The geoip database is updated automatically.
However, the file name has changed in the downloaded archive.
In the old check.searx.space I guess we were using an old version, and the new version was not used.

searx.space is going to be updated in ~1 hour.

**Comment by return42** [comment]
@nicfab, @unixfox .. is this issue fixed / can we close?

**Comment by nicfab** [comment]
> @nicfab, @unixfox .. is this issue fixed / can we close?

Yes, solved.
Is it possible to remove the red background for AWS?

**Comment by return42** [comment]
> Is it possible to remove the red background for AWS?

As far I remember this was not such easy .. I'm going to close this issue since *country detection* is fixed.

**Comment by unixfox** [comment]
> Is it possible to remove the red background for AWS?

Told you twice there is an issue opened: https://github.com/searxng/searx-space/issues/129

**Comment by nicfab** [comment]
> > Is it possible to remove the red background for AWS?
> 
> Told you twice there is an issue opened: #129

I am sorry.
I forgot it, and I was writing another one just now.
Thanks for the telepathic timing 😀
