### ISSUE TITLE
Do not classify the PING resource as customization

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-space#140]
Related to https://github.com/searxng/searxng/pull/2357.

If this PR is merged, searx-space will classify all the public instances as `C` rank for the HTML test because an unidentified CSS resource will be loaded.

searx-space should exempt this specific resource and not classify it in the HTML test.

**Comment by return42** [comment]
Without looking into the implementation; searx-space seems to ignore the ping (CSS) and classifies the engine as `V`anilla

![image](https://github.com/searxng/searx-space/assets/554536/d476760b-f4f7-4d1d-99ac-dafe9b8f4636)

**Comment by return42** [comment]
I close this issue for now .. if we see issues arising in the next days (when https://github.com/searxng/searxng/pull/2357 has been applied to the instances) any issue, we can reopen on demand.
