### ISSUE TITLE
https://searx.space/ is not updated since 2023.6.5

### ISSUE THREAD

**Issue by return42** [searxng/searx-space#148]
Last update of https://searx.space/ was 2023.6.5.  Seems the update service hangs?

@dalf do you have a clue?

Related comments on #searxng:matrix.org:

- https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$7UikuyjVxvf3rdH3NBzeFMbGOrM1hAmH9nKSUAFap2E?via=libera.chat&via=matrix.org&via=envs.net

- https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$9hozhQkiCpiR31fIcehQvxFrW4LlpHdERl0xHZIc7Zo?via=libera.chat&via=matrix.org&via=envs.net

**Comment by dalf** [comment]
The IPv6 of searx.space seems to be broken.
Since check.searx.space used the IPv6, there were no update.

I've change the configuration to use the IPv4 for now: it should fix the update issue.

**Comment by unixfox** [comment]
@dalf if you are running docker it's recommended to set a static ipv6 and disable Ipv6 RA.

**Comment by return42** [comment]
> The IPv6 of searx.space seems to be broken. Since check.searx.space used the IPv6, there were no update.
> 
> I've change the configuration to use the IPv4 for now: it should fix the update issue.

Is the TLS entry related to the IPv6 issue? -->

![image](https://github.com/searxng/searx-space/assets/554536/9723e9e0-bffc-4977-a674-6dce5f6d57ed)

Related comments on #searxng:matrix.org:

- https://matrix.to/#/!vxScbLNEAmRvOraXBn:matrix.org/$PQRZ7GgF1AiyKiFSUtI58zh92-D6s792I1HNCLd_B9U?via=libera.chat&via=matrix.org&via=envs.net

**Comment by nicfab** [comment]
For me, it’s not only an IPv6 issue because also the E value is wrong.

**Comment by return42** [comment]
@dalf as far I see, the update issue, the IPv6 issue and the rating issue @nicfab mentioned are solved .. I close this issue .. thanks for your work on this :+1:
