### ISSUE TITLE
Back navigation is broken

### ISSUE THREAD

**Issue by Kissaki** [searxng/searx-space#150]
1. Open main page
2. Click About
3. Navigate back

Expected: I see the main page content again.
Actual: No UI change.

The URL path changes between `/#` and ``.

**Comment by return42** [comment]
Theses are tabs (Views) of one and the same URL .. that is why you won't see any history entries in your browser .. so your browser cant "navigate back" to a previous visited URL.

**Comment by Kissaki** [comment]
I see any of the top navigation links sets the `#` path too. That doesn't change the fact that it does change the path.

If the website doesn't use URLs it shouldn't set `#` as a path. That is a different URL to not having it. The browser will always offer back and forth navigation on that.
