### ISSUE TITLE
yacy engine instances

### ISSUE THREAD

**Issue by tekakutli** [searxng/searx-space#151]
I can't find a way to filter https://searx.space to get a list of instances which have yacy enabled
suggesting for it

**Comment by unixfox** [comment]
Go to the engines tab on searx.space.

You should be able to filter by engine.

**Comment by tekakutli** [comment]
that's what I mean, it's not there  
or is it because there are zero instances with yacy enabled?

**Comment by unixfox** [comment]
yacy is optional so no public instances probably have it enabled: https://github.com/searxng/searxng/blob/master/searx/settings.yml#L1732

if you want yacy on searxng, run your own instance.
