### ISSUE TITLE
How to estimate latency to users in different countries (e.g. US)? 

### ISSUE THREAD

**Issue by e-t-l** [searxng/searx-space#154]
It looks like the fastest server by far is https://searxng.nicfab.eu, but that's located in Europe and I'm pretty sure searx.space is as well. I imagine that server would be a lot slower if pinged by users in North America. Is there any way to at least estimate the latency, short of hosting my own searxstats instance?

**Comment by unixfox** [comment]
https://github.com/searxng/searx-space/issues/1
