### ISSUE TITLE
Search response time column: the test must fail when there are only wiki* engines in the result

### ISSUE THREAD

**Issue by dalf** [searxng/searx-space#159]
See https://github.com/searxng/searxng/pull/2806

A lot of instances don't have any more working engines in the general category except wikipedia/wikidata/wiki* engines.

These instance should be marked with "No result".

Technical details: the check here must ignore results with only the `wiki*` engines.
https://github.com/searxng/searx-space/blob/061d06b5b4d68fcea15d99794e4dbb0fb76140fc/searxstats/fetcher/timing.py#L31-L32

**Comment by unixfox** [comment]
:+1:

**Comment by unixfox** [comment]
This is also misleading farside users as they rely on searx.space as a source of truth for using a searxng instance that work.

**Comment by dalf** [comment]
Closed by https://github.com/searxng/searx-space/pull/160
