### ISSUE TITLE
Provide API to search searxng instances

### ISSUE THREAD

**Issue by GunGunGun** [searxng/searx-space#164]
Hello,

SeaxSpace is very neat, but I think it would be even greater to be able to use API to search exactly what we want and what is best for us, for example:
- Get instance by country, this is very very big because using the same country as our country improves speed by a lot
- Get instance by uptime
- ~~Get instance by lifetime~~ https://github.com/searxng/searx-space/issues/152

Which is great to be able to make use of.

**Comment by unixfox** [comment]
What's stopping you from fetching the API https://searx.space/data/instances.json and filtering yourself in your program?

**Comment by GunGunGun** [comment]
> What's stopping you from fetching the API https://searx.space/data/instances.json and filtering yourself in your program?

I see, I didn't know about JSON API but this is very nice, I'll try to use farside in combination with this API to parse and choose best server, thanks!
