### ISSUE TITLE
Help button doesnt work in Tor section

### ISSUE THREAD

**Issue by inson1** [searxng/searx-space#171]
https://searx.space/#help-http-grade

**Comment by unixfox** [comment]
What help button are you talking about? Did you enable JavaScript?

**Comment by inson1** [comment]
@unixfox 
![brave_97PeY7gYNh](https://github.com/searxng/searx-space/assets/75314629/cf39f078-b097-4a34-aa57-7353a1b4724f)

there is no way to link it by url, so should I just create PR witth duplicate from http section?
![brave_vw2mfZNH2A](https://github.com/searxng/searx-space/assets/75314629/e5b59acd-d8b5-4e35-b201-b7d3584c8f2f)

**Comment by unixfox** [comment]
It works for me. Make sure you have JavaScript enabled.

**Comment by inson1** [comment]
In Tor section/page? How? 
![brave_v3EyX7Qyev](https://github.com/searxng/searx-space/assets/75314629/c1e425c5-9f8e-40fd-907d-5f2a02c89a04)
(in brave)
![brave_010IOBA46c](https://github.com/searxng/searx-space/assets/75314629/09dd240b-e09f-437e-a946-c55ede9582d7)
In brave, librewolf, tor it doesnt work

**Comment by unixfox** [comment]
Closing as I don't see the benefit of duplicating the information for the tor section.
One can see it in the first, general section.
