### ISSUE TITLE
Uptime average of public instances

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-space#57]
This is a break down of issue #54 because it contained too many features at the same time.

----------

Track the uptime of public instances. We could use uptime robot or another tool for that and then use their API for fetching the overall uptime. That's what Invidious does with their instances list: https://instances.invidio.us/

**Comment by unixfox** [comment]
Maybe we could use https://github.com/upptime/upptime for tracking the instances health?

We can then fetch the health per month of every instance in a neat json file like here: https://github.com/xnaas/nitter-instances/blob/master/history/summary.json

**Comment by unixfox** [comment]
I spent a couple of hours setting up this repo: https://github.com/searxng/searx-instances-uptime
It is monitoring all the current public instances and will update its list automatically: https://github.com/searxng/searx-instances-uptime/blob/master/.github/workflows/update-sites.yml

I guess searx-space can now take advantage of https://github.com/searxng/searx-instances-uptime/blob/master/history/summary.json and use it to display the uptime per month of every instance (except tor, I'll work on that).

Is adding a column "Uptime" a good idea? Or should it be displayed in another way?

**Comment by dalf** [comment]
In my opinion, we can change the columns in this way:
* from [summary.json](https://raw.githubusercontent.com/searxng/searx-instances-uptime/master/history/summary.json) add:
  * `uptime`
  * `uptimeWeek`
* remove:
  * `Wikipedia response time`: always fast (especially server time).
  * `Initial response time`: I haven't checked, but I think all instances support HTTP/2, so I'm not sure the measure is relevant.

**Comment by unixfox** [comment]
Removing wikipedia response time column in order to replace it with uptimeMonth is a good idea!

I don't think uptimeweek is relevant because it's a too short duration for the users to be sure that they won't get an instance that is half of the time down.

About `Initial response time`, I think it's better to open a new issue in order to discuss the removal. At least if we remove the wikipedia column we have space for the uptime column.

Maybe we could display the uptime details of day, week, year and overall when hovering the mouse on the percentage. Like it's already the case for most of the column details.
![image](https://user-images.githubusercontent.com/4016501/172019721-4d00ec67-10ca-4724-9449-089d319325c7.png)

And we could make that number clickable so that the user can access to the graph of the uptime of the instance on uptime.searxng.org

**Comment by dalf** [comment]
Implemented in https://github.com/searxng/searx-space/pull/124 : 
* remove the wikipedia response time
* display the uptime of the week 
* the tooltip contains the uptime for the current day, week, month and year
* link to https://uptime.searxng.org/

I leave the issue open the time searx.space gets at least one update.
