### ISSUE TITLE
/config : GIT_URL is ignored

### ISSUE THREAD

**Issue by dalf** [searxng/searx-space#76]
* For https://searx.be/ GIT_URL = 'unknown', the detected fork is https://github.com/paulgoio/searx
* For https://darmarit.org/searx/ GIT_URL is https://github.com/return42/searxng

In both cases, the detected fork is https://github.com/paulgoio/searx
It should be https://github.com/searxng/searxng

**Comment by dalf** [comment]
See https://github.com/paulgoio/searx/commit/3e3049f2944e667c1cbf1e08a33d9d93d74c23aa

Static content from searxng are also included in paulgoio fork, so the hashes of the static files belong to two repositories.

Possible improvement: link each hash only to the oldest commit.

**Comment by unixfox** [comment]
https://darmarit.org/searx/ seems to be affected too.

**Comment by dalf** [comment]
#77 is a partial fix.

When git_url  = 'unknow', a possible solution is to record the commit date, and then give priority to the oldest commits (whatever the fork).

**Comment by return42** [comment]
Hm, I do not understand why `searx.version.GIT_URL` is _unknow_.

> https://darmarit.org/searx/ seems to be affected too.

Setup is here https://github.com/return42/searxng/commit/245947e8df0edd48a849880bc756a5548165a8d3

And it seems to shown correct ...

![grafik](https://user-images.githubusercontent.com/554536/129949397-d9fdb22f-a463-49f7-ab26-fb461b6e338f.png)

The only thing I miss is the GIT_BRANCH value, therefore I send  https://github.com/searxng/searxng/pull/263

**Comment by dalf** [comment]
@return42 multiple reasons:
* some git repositories were not updated (some exceptions were not catched).
* one commit on paulgoio forks contains all the static file from searxng: 
-->
searxstats saw the static files were belonging to paulgoio not to return42 (because the git repository was not updated)
-->
the git_url were replaced:
https://github.com/searxng/searx-space/blob/b23b4a507126b2793e8db81db6763333074e7d08/searxstats/fetcher/external_ressources.py#L345-L346

Now, the git repository updates should be more reliable, and issue _should_ not occur again.

---

About searx.be: since the GIT_URL is unknow in /config (sorry for breaking change here), searxstats tries to detect the GIT_URL.
There are two candidates: return42 and searxng forks with the same commits. Here the priority is given to forks in this hard coded list:
https://github.com/searxng/searx-space/blob/b23b4a507126b2793e8db81db6763333074e7d08/searxstats/config.py#L68-L73

A possible enhancement is to query the GitHub API to know which repository is fork of the other:
https://api.github.com/repos/return42/searxng see `parent`.

Side note: to configure the GIT_URL value of the /config endpoint, see: https://github.com/paulgoio/searx/blob/324d26b9b26c08922fa304fb6b9b907378bc2f40/Dockerfile#L16-L17

---

searx.space will be updated in few hours.

**Comment by unixfox** [comment]
https://searx.be/config fixed

**Comment by dalf** [comment]
searx.space now:
| URL | GIT_URL |
|---------------------|---------------------|
| https://searx.be/ | https://github.com/searxng/searxng |
| https://start.paulgo.io/ | https://github.com/paulgoio/searx |
| https://spot.ecloud.global/ | https://gitlab.e.foundation/e/cloud/my-spot |
| https://darmarit.org/searx/ | https://github.com/return42/searxng |

**Comment by return42** [comment]
@dalf thanks for explanations and fixes / FYI I updated my instance, https://darmarit.org/searx/config now includes the branch ..

![image](https://user-images.githubusercontent.com/554536/130234402-f2b1acf0-57b5-41be-90bb-fb8d1150efd4.png)

> A possible enhancement is to query the GitHub API to know which repository is fork of the other:

Hm, GitHub API  is nothing I would enforce .. not all forks are located at gihub :-)
