### ISSUE TITLE
searx.space can't scan https://anon.sx

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-space#81]
![image](https://user-images.githubusercontent.com/4016501/133314421-8d7b40e6-3397-48a4-9b15-0ea652814814.png)

**Comment by dalf** [comment]
It has been "fixed" (ping anon.sx works): it is a DNSSec issue.

`check.searx.space` uses a local unbound with this DNSSec configuration:
```
    harden-algo-downgrade: yes
    harden-glue: yes
    harden-below-nxdomain: yes
    harden-dnssec-stripped: yes
    harden-referral-path: yes
    aggressive-nsec: yes
```

logs with this configuration:
```
debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_reply
debug: cache memory msg=181011 rrset=233223 infra=65488 val=153337 subnet=140552
info: subnet operate: query anon.sx. A IN
debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
info: Could not establish a chain of trust to keys for sx. DNSKEY IN
info: validator operate: query anon.sx. A IN
debug: validator[module 1] operate: extstate:module_wait_subquery event:module_event_pass
info: subnet operate: query ns2.ns.sx. AAAA IN
debug: subnet[module 0] operate: extstate:module_state_initial event:module_event_moddone
info: Could not establish a chain of trust to keys for sx. DNSKEY IN
info: validator operate: query ns2.ns.sx. AAAA IN
debug: validator[module 1] operate: extstate:module_wait_subquery event:module_event_pass
info: Did not match a DS to a DNSKEY, thus bogus.
debug: Failed to match any usable DS to a DNSKEY.
info: Did not match a DS to a DNSKEY, thus bogus.
debug: Failed to match any usable DS to a DNSKEY.
info: subnet operate: query sx. DNSKEY IN
debug: subnet[module 0] operate: extstate:module_wait_module event:module_event_moddone
info: validator operate: query sx. DNSKEY IN
debug: validator[module 1] operate: extstate:module_wait_module event:module_event_moddone
info: finishing processing for sx. DNSKEY IN
info: query response was ANSWER
info: reply from <sx.> 185.159.198.10#53
info: response for sx. DNSKEY IN
info: iterator operate: query sx. DNSKEY IN
```

I have to comment out `harden-algo-downgrade` and `harden-dnssec-stripped` to make it work ( https://nlnetlabs.nl/documentation/unbound/unbound.conf/ )

       harden-algo-downgrade: <yes or no>
              Harden  against algorithm downgrade when multiple algorithms are
              advertised in the DS record.  If no, allows  the  weakest  algo-
              rithm  to  validate the zone.  Default is no.  Zone signers must
              produce zones that allow this feature  to  work,  but  sometimes
              they  do not, and turning this option off avoids that validation
              failure.

       harden-dnssec-stripped: <yes or no>
              Require  DNSSEC  data  for trust-anchored zones, if such data is
              absent, the zone becomes bogus. If turned  off,  and  no  DNSSEC
              data  is  received  (or the DNSKEY data fails to validate), then
              the zone is made insecure, this behaves like there is  no  trust
              anchor.  You  could turn this off if you are sometimes behind an
              intrusive firewall (of some sort) that removes DNSSEC data  from
              packets,  or  a  zone  changes  from signed to unsigned to badly
              signed often. If turned off you run the risk of a downgrade  at-
              tack that disables security for a zone. Default is yes.

---

Related to #19 and  #74

**Comment by unixfox** [comment]
If you disabled DNSSec just for this domain then please enable it back :), we don't have to weaken our security for a misconfiguration on the searx instance maintainer side.

@jnnngs as the author of https://anon.sx, can you fix your DNSSec configuration?

**Comment by dalf** [comment]
The purpose of #74 is to [check DNSSec validity, the result can be either](https://github.com/searxng/searx-space/blob/4ca823ac4a28fe079679120f309aa426aef286b2/searxstats/fetcher/network.py#L135-L163):
* secured
* unsecured
* bogus

I was expecting to see "bogus" about anon.sx but it is "unsecure":
![image](https://user-images.githubusercontent.com/1594191/133382474-1e616d7e-ffe8-4745-b0dc-c605b3caf956.png)

I would like to investigate this.

**Comment by dalf** [comment]
With the hardening configuration:
* ldns returns bogus as expected ( https://gist.github.com/dalf/ed255cba5d9d19ff2eb17d6fe9fe2736 )
* before the ldns test, a simple HTTP request is sent to the instance. This request fails with the message "[Errno -3] Temporary failure name resolution" since the DNSSec check fails. Since this simple test fails the instance is seen as offline.

A possible solution to this chicken/egg problem:
* two DNS servers: 
   * the default server without DNSSec for searx-space.
   * a second server with DNSSec only to check the DNSSec configuration (and also the DNS server for the host)

**Comment by jnnngs** [comment]
> If you disabled DNSSec just for this domain then please enable it back :), we don't have to weaken our security for a misconfiguration on the searx instance maintainer side.
> 
> @jnnngs as the author of https://anon.sx, can you fix your DNSSec configuration?

Hi Guys,

Happy to do whatever I need to do. I'm using letsencrypt and njal.la for DNS. Can you point me in the right direction to fix DNSSec config?

**Comment by jnnngs** [comment]
Looks like njal.la doesnt support DNSSEC for .sx domains. Do you know if its possible to change nameservers to a different register that does? If so, recommend anything to keep the privacy? Cloudflare is an avoid, even with CDN proxy disabled?

**Comment by dalf** [comment]
> If you disabled DNSSec just for this domain then please enable it back :)

Done since few days.

---

> Looks like njal.la doesnt support DNSSEC for .sx domains.

I'm knew to njal.la, it's seems they usually supports DNSSec :(

https://check.njal.la/dns/?name=anon.sx

> Do you know if its possible to change nameservers to a different register that does?

* you can change the NS records to another provider (I've never done that).
* you can transfer your domain to another registrar.

> Cloudflare is an avoid, even with CDN proxy disabled?

From the privacy point of view: yes, Cloudflare will see the user queries in clear.

(searx.space will display the network name with a red background).
