### ISSUE TITLE
Onion/Tor instances are all returning error

### ISSUE THREAD

**Issue by MarcAbonce** [searxng/searx-space#95]
Today I realised that none of the onion/Tor instances appear in searx.space and all return the same error.

#### How To Reproduce
1. Go to the **Online Tor** tab in https://searx.space
1. 0 online instances appear.
1. Go to **Offline & error** tab.
1. All the onion instances appear under **Unknown host** with the same error message: `[Errno -2] Name or service not known`

I think the bug was probably introduced in https://github.com/searxng/searx-space/commit/729fdf7d151cf8ca4ab674bfd693888817fabdc3 because the 'proxies' kwarg is not being passed to AsyncClient anymore.
```diff
diff --git searxstats/common/http.py
@@ -66,9 +66,7 @@ async def new_client(*args, **kwargs):
            network_type = kwargs['network_type']
            kwargs['proxies'] = NETWORK_PROXIES.get(network_type, None)
        del kwargs['network_type']
-    if 'backend' not in kwargs:
-        kwargs['backend'] = get_httpx_backend()
-    async with httpx.AsyncClient(*args, **kwargs) as session:
+    async with httpx.AsyncClient(*args, backend='asyncio', verify=SSL_CONTEXT) as session:
        session._network_type = network_type  # pylint: disable=protected-access
        yield session
```

**Comment by dalf** [comment]
The issue is fixed on searx.space
Thank you for the detailed report.
