### ISSUE TITLE
Regarding potential privacy issues with current display of instances on searx.space

### ISSUE THREAD

**Issue by tiekoetter** [searxng/searx-space#97]
_This is not meant to attack any instance maintainer personally._

Currently only TLS + CSP + Search response time determines which instance is at the top of the list. This would be fine if no instance maintainer would employ things that are regarded as "bad" by the consensus.

Examples of this bad things would be:
1. using Server in the ASN of Akamai, Alibaba, Amazon, Aryaka Networks Inc., Azure, Cloudflare, CDNetworks Inc., EdgeCast Networks Inc., Highwinds Network Group Inc., Incapsula Inc., Instart Logic Inc., Fastly, Google, Limelight or Yottaa Inc.
2. Using Analytics
3. Using query response caching(?)

**Regarding 1.:**
Currently only the ASN is "penalized"; by giving it a red background. It seems to not affect ranking however as instances with similar TLS + CSP but higher Search response time will be ranked below such an engine.
<img width="1401" alt="Bildschirmfoto 2022-02-01 um 23 07 08" src="https://user-images.githubusercontent.com/77782671/152059625-75136045-5cbc-4987-bf16-4ab54665e3d6.png">

**Regarding 2.:**
The implementation of how a user is warned about an instance, which is using analytics of any kind, is ambiguous. It just doesn't make sense to use the comment to inform the user about analytics when the same comment is used to inform the user that the instance has a hidden service version for example.
<img width="1414" alt="Bildschirmfoto 2022-02-01 um 23 10 50" src="https://user-images.githubusercontent.com/77782671/152061332-f4ac06fd-bc1c-4a53-ab4b-1c663c223b14.png">
<img width="1412" alt="Bildschirmfoto 2022-02-01 um 23 15 11" src="https://user-images.githubusercontent.com/77782671/152061345-9c45a8a4-88ab-418d-82e6-f32ea78aefdc.png">
<img width="1402" alt="Bildschirmfoto 2022-02-01 um 23 22 38" src="https://user-images.githubusercontent.com/77782671/152061506-6827dd49-0b22-4256-8d3f-02f0c3d8ca50.png">

**How to approach the issue:**
The ranking needs to be changed to include something like a debuff for offending instances.
My idea: 
Including analytics in searx / SearXNG can't be done accidentally, so it needs to be penalized the most. 
A penalty for analytics needs to be bigger than a penalty for the ASN.
Offending instances will be put on the bottom of their TLS + CSP rating regardless of Search response time. Instances who only have a "wrong" ASN will always be ranked higher than instances which have analytics. The combination of both is ranked the lowest.
A separate column needs to be added in front of the TLS + CSP + HTML rating. A possible name could be "Privacy conform" where conforming instances have a green tick in it and non conforming ones have a red cross. Non conforming instances should have a hover text where it is explained why it is not conforming (so mentioning the analytics and/or the ASN).

**Why should we care?**
"Search without being tracked.", "[...] Users are neither tracked nor profiled. [...]" (https://docs.searxng.org/)
To conform to this statement we can't allow the top-instance (so currently serx.cf) to be an instance which throws the ideals of searx out of the window. 
If someone new finds out about searx / SearXNG and wants to try a public instance but sees that the top instance uses analytics, it probably won't help to convince them about the project. This goes against everything this project stands for.

---
Please voice your opinion.

**Comment by TordenskjoldJr** [comment]
I came across this project relatively recently and am currently working on setting up my own public instance. I was also very surprised to see an instance that uses analytics listed on the top of the page.

Of course everyone can run his instance as he wants and you can say "then just don't use this instance", but in my opinion the use of analytics is against the actual principle of searx or searxng, at least that's how I understood the project.

The suggestion with better identifiability and lower placement of such instances is very good. For new users, and of course for everyone in general, it should be more recognizable.

**Comment by dalf** [comment]
Automatic detection of analytics is not straightforward (?)

So I suggest to add a field `analytics` in https://github.com/searxng/searx-instances/blob/master/searxinstances/instances.yml : 
* `false` by default
* can be `true`.

Then searx-space can use that new field to sort the instances.

**Comment by unixfox** [comment]
> Automatic detection of analytics is not straightforward (?)
> 
> So I suggest to add a field `analytics` in [https://github.com/searxng/searx-instances/blob/master/searxinstances/instances.yml](https://github.com/searxng/searx-instances/blob/master/searxinstances/instances.yml?rgh-link-date=2022-02-02T13%3A16%3A32Z) :
> 
>     * `false` by default
> 
>     * can be `true`.
> 
> 
> Then searx-space can use that new field to sort the instances.

I'm ok with that, mainly because I could just have an external program (not written in python) that look for analytics software and report that in the terminal.

It would be some manual intervention at first but I'm fine with that. The public can help too because the instances list is publicly available.

What's the letter we give for instances with analytics? The letter A or display an eye with some red around it? Like so ?:
<img width="54" alt="image" src="https://user-images.githubusercontent.com/4016501/152314745-a479e3bd-c888-4019-acd5-0d7e2d2b7f54.png">
Unicode of the eye used: https://unicode-table.com/en/1F441/

**Comment by unixfox** [comment]
Feature implemented.
